In [18]:
#two ways to generally indicate missing data
#mask
##store the location of missing data in an array
##con: additional overhead due to another array

#sentinal value
##null value is represented by a rare value eg: -9999, nan
##con: not all values can be represented by NaN

#Pandas goes the Sentinel Value route. They use either NaN or None

#None is a singleton object. It therefore can be used in arrays
import numpy as np
import pandas as pd

vals1 = np.array([1,None,2,3,4])
vals1
#note that None is not an int object. since the array contains int, numpy treats
##this array as a list of objects

array([1, None, 2, 3, 4], dtype=object)

In [19]:
##this is not the most efficient
for dtype in ['object','int']:
    print("dtype =", dtype)
    #create a numpy array with 5 evenly split elements. once as an object. 
    #another as an int. 
    #and sum all values together
    %timeit np.arange(5, dtype = dtype).sum()

dtype = object
6.51 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
dtype = int
6.9 µs ± 566 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [20]:
#furthermore, using the object type in general causes errors with arithmetic functions
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [23]:
#NaN or Not a Number is different than none
#note that with nan the object is float64
vals2 = np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [25]:
#NaN will override all other values
1 + np.nan

nan

In [30]:
#this override will affect any arithmetic function
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [32]:
#you can use special functions to overcome this behaviour tho
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [35]:
#pandas will automatically alter the values of other datatypes to work with NaN
##eg an int will convert to a float
pd.Series([1,1,np.nan,3,None])

0    1.0
1    1.0
2    NaN
3    3.0
4    NaN
dtype: float64

In [41]:
x = pd.Series(range(2),dtype=int)
print(x)
x[0]= None

##when you change one of the series values to NaN, the entire array is upcast as a float
print(x)

0    0
1    1
dtype: int32
0    NaN
1    1.0
dtype: float64

In [43]:
#pandas has native functions for working will nulls
#isnull() = detects nulls 
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [46]:
#notnull() = returns a boolean array of not null values
## you can use the output of this function as a boolean mask
data[data.notnull()]

0        1
2    hello
dtype: object

In [47]:
#dropna() = will drop the null values
data.dropna()

0        1
2    hello
dtype: object

In [51]:
#these functions have a slightly different behaviour with dataframes over series
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

#dropna() will drop any rows with missing values
df.dropna()

#dropna(axis='columns') will drop any columns with missing values
df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [55]:
#but you may want to be more selective in what data you drop. You would use the 
##how and thresh parameters
df[3] = np.nan
df

#how = 'all' will only drop the values in a column if all the values are null
df.dropna(axis='columns', how = 'all')

#this will only drop null rows if the row contains at least 3 datapoints
df.dropna(axis='rows', thresh=3)

     0    1  2   3
1  2.0  3.0  5 NaN

In [60]:
#you can fill nan values with fillna()
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))

#this fills missing values with 0
data.fillna(0)

#this fills missing values with the prior value(forwardfill)
data.fillna(method='ffill')

#this fills missing values with the later value(backwardfill)
data.fillna(method='bfill')

#you can specify the axis in which this kind of ffill or bfill occurs
#this does a ffill based of the columns
df.fillna(method='ffill',axis=1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0